from .utilizzatore import Utilizzatore
from .cliente import Cliente
from .skiman import SkiMan
from .amministratore import Amministratore
from .servizio import Servizio
from .attrezzatura_principale import AttrezzaturaPrincipale
from .sci import Sci
from .snowboard import Snowboard
from .scarpone import Scarpone
from .casco import Casco
from .armadietto import Armadietto
from .carnet import Carnet
from .prenotazione import Prenotazione
from .assegnamento import Assegnamento
from .ricevuta import Ricevuta
